### ISSUE TITLE
rr_openrover* source repositories don't exist

### ISSUE THREAD

**Issue by tfoote** [RoverRobotics/roverrobotics_ros1#12]
There are several rr_openrover_* packages in kinetic rosdistro where the source repository doesn't exist.

This looks to be the most likely successor package so I'm filing this for visibility.

https://github.com/ros/rosdistro/issues/26853

I will be delisting the broken references in the rosdistro.

**Comment by drhieu** [comment]
I think you are looking for https://github.com/RoverRobotics/roverrobotics_stack. and not this repo. That repo should have everything that you need
