### ISSUE TITLE
Rover rotates violently when the input command is just linear speed.

### ISSUE THREAD

**Issue by nknxr** [RoverRobotics/roverrobotics_ros1#22]
Hi all,

Rover rotates at a very high speed when the input twist message is just low linear speed. This strange behavior is observed at three different rovers with the new driver. This happens less frequently but still need to be fixed.

I ran the pro.launch with everything same except for twist_mux config file. I have attached the bag file and twist_mux config file for reference.
[Link to the bag file](https://drive.google.com/drive/folders/17IqgiOBEK8Bw0_dhCHBJfdvHpYmqR1pp?usp=sharing)

Usually I restart the pro.launch to fix this issue. Can we have a patch to fix this issue?
Thanks.

**Comment by nknxr** [comment]
I wasn't using a controller. I was using rqt_robot_steering. 

Negative linear speed makes the rover rotates clockwise while positive linear speed makes the rover rotate anti-clockwise.

**Comment by nknxr** [comment]
In closed loop mode.

**Comment by nknxr** [comment]
I restarted the driver while back. But from my previous observation, I directly published Twist() message on /cmd_vel/managed topic. So, it bypasses both input_manager and twist_mux. It had the same behavior.

**Comment by drhieu** [comment]
Please output these [variables](https://github.com/RoverRobotics/roverrobotics_ros1/blob/f949731092853fdd1c631f1b497e1123a9c7eeb8/roverrobotics_driver/src/roverrobotics_ros_driver.cpp#L308-L310) to the console to verify that you are getting valid output from ROS.
