### ISSUE TITLE
Unexpectedly disconnected from serial port

### ISSUE THREAD

**Issue by maxpolzin** [RoverRobotics/roverrobotics_ros1#23]
When launching "roslaunch roverrobotics_driver zero2_teleop.launch", I receive a fatal error message "Unexpectedly disconnected from serial port. Check connection to robot and reset Estop" and the roverrobotics_driver shuts down.

Ubuntu 18.04 / ROS Melodic
librover: 3.1.1
roverrobotics_ros1: 3.1.1

![image](https://user-images.githubusercontent.com/20051567/141329844-bb2952f7-705d-46d6-8f41-71f68f385284.png)
![image](https://user-images.githubusercontent.com/20051567/141329949-d1498f77-1285-453f-8b55-c02fc56caebb.png)

**Comment by drhieu** [comment]
Hi max
This error show up when (your robot is disconnected, estop is triggered, or your VESC is disconnected)
Based on your ls dev output. It is likely that your vesc is disconnected internally.

**Comment by maxpolzin** [comment]
Thanks a lot for the fast response @drhieu. I will open the chassis and check if the VESC is connected.

**Comment by maxpolzin** [comment]
The battery was not connected to the VESC. It might be nice to have a hint on the packaging. Maybe it was there and I simply oversaw it. Again thank you for your fast response and help.
