### ISSUE TITLE
Possibly wrong 4WD_Rover config file

### ISSUE THREAD

**Issue by samaleksandrov** [RoverRobotics/roverrobotics_ros1#31]
Hi, 

I'm trying to run a simulation with our 2WD Rover Pro which has an R&D payload and we mounted a LiDAR on top. There are two issues:
- In /roverrobotics_description/launch/description-2wd.launch as a config is stated 4WD_Rover_with_SLAM_pack. IMO there shall be a 2WD config with or without SLAM pack available or at least more general naming if the configs are identical.
- As soon as you try to launch the same file with 4WD_Rover as a config file, the launch fails. 
A workaround was to comment out the accessories in the roverrobotics_description/urdf/2WD_Rover/2WD_rover.urdf.xacro (line 5) and then it loads the robot model without an issue.

Is it possible to revisit the config files and fix that or share how this shall we used, in case one doesn't want to use the SLAM pack option? Thanks in advance!

**Comment by samaleksandrov** [comment]
ping

**Comment by RoverRoboticsProduction** [comment]
This is a good workaround, we are not going to be adjusting the config files at this time but we will make note of your workaround and make that information available.
